### ISSUE TITLE
Signal Controls reading zeroes

### ISSUE THREAD

**Issue by Jimbomonkey** [Observatory-Sciences/dls-pmac-control#2] opened 2021-12-16 11:57 UTC
For some axes, when I go to settings | PID and macro, and look at the Signal controls values (loop select, capture on, capture flag, output mode) they all report 0.  If I try to set the correct value, it immediately changes back to 0.

![Screenshot from 2021-12-16 11-55-57](https://user-images.githubusercontent.com/6267062/146367449-af4e12de-757a-4e1e-8f85-64acd033c447.png)

If I connect to the same brick using the old version (dls_pmaccontrol/1-12-8) these values are all reported back correctly

![Screenshot from 2021-12-16 11-56-13](https://user-images.githubusercontent.com/6267062/146367445-cd5ef49d-b2b4-4aa3-9412-2c62eac9158a.png)

I can demonstrate this on bl03i-mo-step-08

**Comment by rjwills28** [comment] 2022-01-11 11:41
Thanks for reporting this. We have now fixed this issue which was caused by a bug in the Python2 -> Python3 conversion in the dls-pmac-lib software. The software was attempting to do integer division to determine the I variable number which works in Python 2, but requires a different syntax in Python 3 to ensure the result remains an integer value.

For more details see commit: https://github.com/Observatory-Sciences/dls-pmac-lib/commit/8d4069ce14b19d623a0131f1bc00e95602298901

This fix has been included in the DLS 3.0.0b2 version.

**Closed as completed** 2022-02-18 12:35 UTC
